# Generated by Django 3.2.9 on 2021-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=10)),
                ('place_origin', models.CharField(max_length=10)),
                ('cat_weight', models.CharField(max_length=11)),
                ('cat_info', models.TextField(verbose_name='기본정보')),
                ('cat_character', models.TextField(verbose_name='성격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='blog/post/%Y/%m/%d/%H')),
            ],
        ),
    ]
