# Generated by Django 3.2.9 on 2021-11-29 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworkapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messageboard',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
