# Generated by Django 3.2.9 on 2021-11-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworkapp', '0003_alter_messageboard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='작성시간'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='작성시간'),
        ),
    ]
