# Generated by Django 3.2.9 on 2021-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworkapp', '0004_auto_20211129_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
