# Generated by Django 3.2.9 on 2021-11-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworkapp', '0005_alter_messageboard_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성시간'),
        ),
    ]
