# Generated by Django 3.2.9 on 2021-11-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworkapp', '0008_alter_messageboard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='date',
            field=models.DateTimeField(verbose_name='작성시간'),
        ),
    ]
