# Generated by Django 3.2.9 on 2021-11-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworkapp', '0011_auto_20211129_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='content',
        ),
    ]
