# Generated by Django 3.2.9 on 2021-11-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworkapp', '0012_remove_messageboard_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='title',
        ),
    ]
