# Generated by Django 3.2.9 on 2021-11-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworkapp', '0013_remove_messageboard_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='title',
            field=models.CharField(default=1, max_length=20, verbose_name='제목'),
            preserve_default=False,
        ),
    ]
