# Generated by Django 3.2.9 on 2021-11-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homeworkapp', '0014_messageboard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='title',
            field=models.CharField(max_length=10, verbose_name='제목'),
        ),
    ]
