# Generated by Django 3.2.9 on 2021-12-12 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='telephone',
            field=models.CharField(help_text='입력예시) 050-1234-5678', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{4}-?\\d{4}-?\\d{4}$', message='전화번호를 입력해주세요.')]),
        ),
    ]
