# Generated by Django 3.2.9 on 2021-11-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
